### ISSUE TITLE
A question about TcwOpti

### ISSUE THREAD

**Issue by TongLing916** [tum-vision/LDSO#19]
Hello, after reading the codes, I found out that every keyframe has  a `TcwOpti` for saving the pose before and after pose graph optimization. What confuses me is that you initializes `TcwOpti` [here](https://github.com/tum-vision/LDSO/blob/master/src/frontend/FullSystem.cc#L414), before sliding window optimization. Wouldn't it be better if you initialize it after sliding window optimization, then update it after pose graph optimization when detecting loops?

**Comment by NikolausDemmel** [comment]
At a quick glance I agree that it probably would make sense to update the optimized pose after sliding window optimization, just before adding the frame to the global map. I guess it doesn't make much difference since the relative poses used in pose graph optimization are recorded using the optimized poses so after pose graph optimization this slight inaccuracy should be "forgotten". However, it might make a small difference if PGO doesn't actually run and in the end we look at `TcwOpti` as the final estimator output. Looks like then they don't have the "best" available pose estimate as you say.

May @gaoxiang12 has more insight?
