### ISSUE TITLE
High memory usage by own sequence

### ISSUE THREAD

**Issue by Xiang-Zhao-de** [tum-vision/LDSO#5]
Thanks for the impressive work! I've met one problem by using my own sequence. The memeory usage grows rapidly and then my laptop died. The memory of my laptop is 8GB, which is not too small. I've tried the TUM-Mono dataset sequence 34. The LDSO works very good and the maximal memory usage is about 1,7GB. Can anybody help me with this problem? Anything wrong with my own sequence? Note: I have no global shutter camera, so I made my own sequence with GoPro.

**Comment by gaoxiang12** [comment]
Hi @Xiang-Zhao-de ,
please check if you are getting too many keyframes so that LDSO tries to save too much data. When I was testing DSO on EUROC I adjust some key-frame picking thresholds to get less key-frames. DSO has some indicators in CoarseTracker which are used to judge if the current frame is a keyframe or not.

**Comment by YipuZhao** [comment]
@gaoxiang12 I have a follow-up question regarding memory consumption.  When running LDSO on long sequence such as NewCollege (40 min), the memory could easily reach ~15GB at half way.  Actually it never finish the whole track as LDSO will drain all memory of my machine.  

At first I thought it was due to growing number of KF being saved for loop closing.  However, even without enabling loop closing module, it still consumes memory quickly.  I am confuses at this point: 
since DSO uses a sliding window filter, it should have much accumulated memory consumption.  Is there any flag that I should turn on / off to control the memory consumption?  

Appreciate any suggestions:)

**Comment by gaoxiang12** [comment]
Hi @YipuZhao Even when loop closing is disabled, the FullSystem class will still save the frame history, and the visualization part will also keep the rendered trajectory and point cloud, which may be the main reason of memory cost. To avoid this, I would suggest you to modify the FullSystem class to remove the inactive keyframes, and also disable the visualization when testing large sequences. Unfortunately there's no explicit flags you can turn on or off for now. I'm afraid you may probably have to change some hard code by yourself.

**Comment by YipuZhao** [comment]
@gaoxiang12 Thank you so much for the suggestion!  Visualizing all the points is definite the major reason of memory consumption.

**Comment by NikolausDemmel** [comment]
I'll close this, since the main memory issue seems to be addressed. If needed, we can reopen.
